"""Curated learning content for the Duolingo-style AI concepts app.

Original questions. Every question has the same shape so the client engine can
treat true/false as a two-option multiple choice:

    {"q": str, "options": [str, ...], "answer": int (index), "concept": str,
     "explain": str}
"""

UNITS = [
    {
        "id": "foundations",
        "title": "AI Foundations",
        "icon": "🧠",
        "lessons": [
            {
                "id": "what-is-ai",
                "title": "What is AI?",
                "questions": [
                    {"q": "What does machine learning let a computer do?",
                     "options": ["Follow only hand-written rules", "Learn patterns from data to make predictions", "Run faster than other programs", "Store more files"],
                     "answer": 1, "concept": "machine-learning",
                     "explain": "ML systems learn patterns from examples (data) instead of being explicitly programmed with rules."},
                    {"q": "True or false: an AI model is just a database of stored answers.",
                     "options": ["True", "False"], "answer": 1, "concept": "what-is-a-model",
                     "explain": "A model learns general patterns; it doesn't simply look up stored answers."},
                    {"q": "Which of these is an example of AI?",
                     "options": ["A calculator adding numbers", "A spam filter that learns which emails are junk", "A light switch", "A printed dictionary"],
                     "answer": 1, "concept": "ai-examples",
                     "explain": "A spam filter improves from examples — that's learning, not a fixed rule."},
                    {"q": "\"Training\" a model means…",
                     "options": ["Running it to answer questions", "Adjusting it using examples so it improves", "Deleting its memory", "Translating its code"],
                     "answer": 1, "concept": "training",
                     "explain": "Training tunes the model's internal values using example data."},
                ],
            },
            {
                "id": "how-machines-learn",
                "title": "How machines learn",
                "questions": [
                    {"q": "In supervised learning, the training data includes…",
                     "options": ["No labels at all", "Correct answers (labels) to learn from", "Only images", "Random noise"],
                     "answer": 1, "concept": "supervised-learning",
                     "explain": "Supervised learning uses labeled examples (input → correct answer)."},
                    {"q": "True or false: unsupervised learning finds structure in data without labeled answers.",
                     "options": ["True", "False"], "answer": 0, "concept": "unsupervised-learning",
                     "explain": "Unsupervised methods (like clustering) discover patterns without labels."},
                    {"q": "\"Inference\" is when a model…",
                     "options": ["Is being trained", "Makes a prediction on new input", "Is deleted", "Is copied"],
                     "answer": 1, "concept": "inference",
                     "explain": "Inference is using a trained model to make predictions."},
                    {"q": "Overfitting means a model…",
                     "options": ["Works great on new data", "Memorizes training data but fails on new data", "Runs too slowly", "Uses too little memory"],
                     "answer": 1, "concept": "overfitting",
                     "explain": "An overfit model memorizes its training set and generalizes poorly."},
                ],
            },
        ],
    },
    {
        "id": "language-models",
        "title": "Language Models",
        "icon": "💬",
        "lessons": [
            {
                "id": "tokens-context",
                "title": "Tokens & context",
                "questions": [
                    {"q": "LLMs read and generate text in units called…",
                     "options": ["Bytes", "Tokens", "Pixels", "Frames"],
                     "answer": 1, "concept": "tokens",
                     "explain": "Text is split into tokens — roughly ¾ of a word on average."},
                    {"q": "True or false: the \"context window\" is the maximum amount of text a model can consider at once.",
                     "options": ["True", "False"], "answer": 0, "concept": "context-window",
                     "explain": "The context window caps how much text the model can attend to in one go."},
                    {"q": "Roughly, one token is about…",
                     "options": ["Ten words", "Three-quarters of a word", "A full sentence", "A paragraph"],
                     "answer": 1, "concept": "tokens",
                     "explain": "A common rule of thumb is ~4 characters or ¾ of a word per token."},
                    {"q": "If a conversation grows past the context window, the model…",
                     "options": ["Remembers everything forever", "May lose the earliest parts", "Crashes", "Gets faster"],
                     "answer": 1, "concept": "context-window",
                     "explain": "Older text can fall out of the window and be forgotten."},
                ],
            },
            {
                "id": "prompting",
                "title": "Prompting basics",
                "questions": [
                    {"q": "A \"prompt\" is…",
                     "options": ["The model's price", "The input and instructions you give the model", "A type of GPU", "An error message"],
                     "answer": 1, "concept": "prompt",
                     "explain": "The prompt is everything you send the model to steer its response."},
                    {"q": "True or false: giving examples in your prompt (few-shot) can improve results.",
                     "options": ["True", "False"], "answer": 0, "concept": "few-shot",
                     "explain": "Showing examples of the format/answer you want often helps a lot."},
                    {"q": "Raising the \"temperature\" setting usually makes output…",
                     "options": ["More random and varied", "Shorter", "Cheaper", "More accurate"],
                     "answer": 0, "concept": "temperature",
                     "explain": "Temperature controls randomness: higher = more varied, lower = more focused."},
                    {"q": "Which is the clearest prompt?",
                     "options": ["\"do the thing\"", "\"Summarize this email in 2 bullet points\"", "\"help\"", "\"?\""],
                     "answer": 1, "concept": "prompt-quality",
                     "explain": "Specific task + format = far better, more reliable results."},
                ],
            },
        ],
    },
    {
        "id": "inside-llm",
        "title": "Inside an LLM",
        "icon": "⚙️",
        "lessons": [
            {
                "id": "embeddings",
                "title": "Embeddings & meaning",
                "questions": [
                    {"q": "An \"embedding\" represents text as…",
                     "options": ["A list of numbers capturing meaning", "A screenshot", "A password", "A URL"],
                     "answer": 0, "concept": "embeddings",
                     "explain": "Embeddings are numeric vectors that capture semantic meaning."},
                    {"q": "True or false: words with similar meaning tend to have similar embeddings.",
                     "options": ["True", "False"], "answer": 0, "concept": "embeddings",
                     "explain": "Similar meaning → vectors that sit close together in space."},
                    {"q": "Embeddings are especially useful for…",
                     "options": ["Semantic search — finding related text", "Charging batteries", "Printing documents", "Compiling code"],
                     "answer": 0, "concept": "semantic-search",
                     "explain": "Comparing embeddings lets you find text by meaning, not just keywords."},
                    {"q": "\"Vector similarity\" measures…",
                     "options": ["File size", "How close two embeddings are in meaning", "Internet speed", "Screen brightness"],
                     "answer": 1, "concept": "vector-similarity",
                     "explain": "Closer vectors = more similar meaning (e.g. cosine similarity)."},
                ],
            },
            {
                "id": "prediction",
                "title": "Prediction & training",
                "questions": [
                    {"q": "At its core, an LLM is trained to…",
                     "options": ["Predict the next token", "Sort numbers", "Compress images", "Route network packets"],
                     "answer": 0, "concept": "next-token-prediction",
                     "explain": "LLMs learn to predict the next token, over and over."},
                    {"q": "True or false: a model's \"parameters\" are the values it learned during training.",
                     "options": ["True", "False"], "answer": 0, "concept": "parameters",
                     "explain": "Parameters (weights) are the tuned numbers that store what it learned."},
                    {"q": "Because LLMs predict likely text, they can sometimes…",
                     "options": ["Never make mistakes", "Produce confident but wrong answers", "Only output code", "Refuse every question"],
                     "answer": 1, "concept": "limitations",
                     "explain": "Fluent ≠ correct — plausible-sounding text can still be wrong."},
                    {"q": "More parameters generally means…",
                     "options": ["Always better and cheaper", "Greater capacity but higher cost", "Smaller files", "No difference"],
                     "answer": 1, "concept": "model-size",
                     "explain": "Bigger models can be more capable but cost more to run."},
                ],
            },
        ],
    },
    {
        "id": "using-ai",
        "title": "Using AI Well",
        "icon": "🚀",
        "lessons": [
            {
                "id": "hallucinations-rag",
                "title": "Hallucinations & RAG",
                "questions": [
                    {"q": "An AI \"hallucination\" is…",
                     "options": ["A graphics glitch", "A confident but false, made-up answer", "A slow response", "A login error"],
                     "answer": 1, "concept": "hallucination",
                     "explain": "A hallucination is fabricated information stated as fact."},
                    {"q": "True or false: RAG gives the model relevant documents so it can ground its answer.",
                     "options": ["True", "False"], "answer": 0, "concept": "rag",
                     "explain": "Retrieval-Augmented Generation supplies real source text as context."},
                    {"q": "RAG helps mainly by…",
                     "options": ["Making text longer", "Reducing made-up answers using real sources", "Changing the font", "Lowering temperature"],
                     "answer": 1, "concept": "rag",
                     "explain": "Grounding answers in retrieved sources cuts down on hallucination."},
                    {"q": "The best way to trust an AI's factual claim is to…",
                     "options": ["Assume it's right", "Verify it against a reliable source", "Ask it twice", "Use a bigger screen"],
                     "answer": 1, "concept": "verification",
                     "explain": "Always verify important facts — the model can be confidently wrong."},
                ],
            },
            {
                "id": "agents-tools",
                "title": "Agents & tools",
                "questions": [
                    {"q": "An AI \"agent\" is a system that…",
                     "options": ["Only chats", "Can plan and take actions using tools", "Sells insurance", "Only stores files"],
                     "answer": 1, "concept": "agents",
                     "explain": "Agents plan steps and use tools (search, code, APIs) to act."},
                    {"q": "True or false: giving an LLM tools lets it act, not just talk.",
                     "options": ["True", "False"], "answer": 0, "concept": "tools",
                     "explain": "Tools turn a text generator into something that can do things."},
                    {"q": "\"Fine-tuning\" a model means…",
                     "options": ["Training it further on specific data for a task", "Deleting it", "Lowering its price", "Translating it"],
                     "answer": 0, "concept": "fine-tuning",
                     "explain": "Fine-tuning adapts a pretrained model to a narrower task or style."},
                    {"q": "A good use of an AI agent is…",
                     "options": ["Automating a multi-step research task", "Replacing all human judgment", "Guaranteeing zero errors", "Nothing at all"],
                     "answer": 0, "concept": "agent-use",
                     "explain": "Agents shine at multi-step tasks — with a human still checking results."},
                ],
            },
        ],
    },
]
